/** @deprecated Import from `./documentStore` — kept for backward compatibility. */
export type { BlendMode, PixelChange, Rgba, TextureLayer } from "./textureDocumentCore";
export {
  addTextureLayer,
  applyPatch,
  canRedo,
  canUndo,
  canvasToPngBase64,
  clearTextureDocuments,
  collectDeltaTextureEntries,
  collectDirtyTextureEntries,
  commitChanges,
  copyRegion,
  ensureTextureDocument,
  getActiveLayerContext,
  getActiveLayerId,
  getActiveLayerCanvas,
  getDirtyTexturePaths,
  getDoc,
  getLayerPixel,
  getOriginalTextureCanvas,
  getPixel,
  getTextureCanvas,
  hasClipboard,
  isTextureDirty,
  listTextureLayers,
  markDirty,
  markTexturesSaved,
  pasteRegion,
  redoTexture,
  removeTextureLayer,
  reorderTextureLayer,
  setActiveLayer,
  snapshotForSave,
  subscribeTextureDocuments,
  undoTexture,
  peekUndoLabel,
  peekRedoLabel,
  updateTextureLayer,
  useDocumentRevision,
} from "./documentStore";

export { compositeDocument } from "./textureDocumentCore";
