// AUTO-GENERATED by export_bindings — do not edit manually.
// Run: npm run gen:types
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
  getAppInfo: () => __TAURI_INVOKE<AppInfo>("get_app_info"),
  ping: () => __TAURI_INVOKE<string>("ping"),
  getSamplePackPath: () =>
    typedError<string, string>(__TAURI_INVOKE("get_sample_pack_path")),
  openSource: (path: string, onEvent: Channel<IndexEvent>) =>
    typedError<OpenSourceResult, CoreError>(
      __TAURI_INVOKE("open_source", { path, onEvent }),
    ),
  reindexProject: (
    handle: ProjectHandle,
    onEvent: Channel<IndexEvent>,
    changedPaths: string[] | null,
  ) =>
    typedError<ReindexResult, CoreError>(
      __TAURI_INVOKE("reindex_project", { handle, onEvent, changedPaths }),
    ),
  invalidateProjectIndex: (handle: ProjectHandle) =>
    typedError<null, CoreError>(__TAURI_INVOKE("invalidate_project_index", { handle })),
  closeSource: (handle: ProjectHandle) =>
    typedError<null, CoreError>(__TAURI_INVOKE("close_source", { handle })),
  cancelIndex: (handle: ProjectHandle) =>
    typedError<null, CoreError>(__TAURI_INVOKE("cancel_index", { handle })),
  queryAssets: (handle: ProjectHandle, filter: AssetFilter, page: PageReq) =>
    typedError<AssetPage, CoreError>(
      __TAURI_INVOKE("query_assets", { handle, filter, page }),
    ),
  getAssetFacets: (handle: ProjectHandle) =>
    typedError<AssetFacets, CoreError>(__TAURI_INVOKE("get_asset_facets", { handle })),
  queryCatalog: (handle: ProjectHandle, filter: CatalogFilter, page: PageReq) =>
    typedError<CatalogPage, CoreError>(
      __TAURI_INVOKE("query_catalog", { handle, filter, page }),
    ),
  getCatalogEntry: (handle: ProjectHandle, entryId: string) =>
    typedError<CatalogEntry, CoreError>(
      __TAURI_INVOKE("get_catalog_entry", { handle, entryId }),
    ),
  getCatalogFacets: (handle: ProjectHandle) =>
    typedError<CatalogFacets, CoreError>(
      __TAURI_INVOKE("get_catalog_facets", { handle }),
    ),
  resolveCatalogEntry: (
    handle: ProjectHandle,
    entryId: string,
    context: StudioResolveContext,
    variantKey: string | null,
  ) =>
    typedError<RenderableModel, CoreError>(
      __TAURI_INVOKE("resolve_catalog_entry", { handle, entryId, context, variantKey }),
    ),
  rebuildProjectCatalog: (handle: ProjectHandle, language: string) =>
    typedError<null, CoreError>(
      __TAURI_INVOKE("rebuild_project_catalog", { handle, language }),
    ),
  getCatalogIconCache: (handle: ProjectHandle, iconKey: string) =>
    typedError<string | null, CoreError>(
      __TAURI_INVOKE("get_catalog_icon_cache", { handle, iconKey }),
    ),
  setCatalogIconCache: (handle: ProjectHandle, iconKey: string, pngBase64: string) =>
    typedError<null, CoreError>(
      __TAURI_INVOKE("set_catalog_icon_cache", { handle, iconKey, pngBase64 }),
    ),
  invalidateCatalogIconsForTextures: (handle: ProjectHandle, texturePaths: string[]) =>
    typedError<string[], CoreError>(
      __TAURI_INVOKE("invalidate_catalog_icons_for_textures", { handle, texturePaths }),
    ),
  getProjectFingerprint: (handle: ProjectHandle) =>
    typedError<string, CoreError>(__TAURI_INVOKE("get_project_fingerprint", { handle })),
  getAssetEntry: (handle: ProjectHandle, assetId: string) =>
    typedError<AssetEntry, CoreError>(
      __TAURI_INVOKE("get_asset_entry", { handle, assetId }),
    ),
  getAssetDetails: (handle: ProjectHandle, assetId: string) =>
    typedError<AssetDetails, CoreError>(
      __TAURI_INVOKE("get_asset_details", { handle, assetId }),
    ),
  getTexturePreviewsBatch: (
    handle: ProjectHandle,
    assetPaths: string[],
    maxSize: number | null,
  ) =>
    typedError<TexturePreviewBatch[], CoreError>(
      __TAURI_INVOKE("get_texture_previews_batch", { handle, assetPaths, maxSize }),
    ),
  revealAssetInFolder: (handle: ProjectHandle, assetPath: string) =>
    typedError<null, CoreError>(
      __TAURI_INVOKE("reveal_asset_in_folder", { handle, assetPath }),
    ),
  getTexturePreview: (handle: ProjectHandle, assetPath: string, maxSize: number | null) =>
    typedError<TexturePreview, CoreError>(
      __TAURI_INVOKE("get_texture_preview", { handle, assetPath, maxSize }),
    ),
  getTexture: (handle: ProjectHandle, texturePath: string) =>
    typedError<TexturePreview, CoreError>(
      __TAURI_INVOKE("get_texture", { handle, texturePath }),
    ),
  // Returns raw PNG bytes via Tauri binary IPC (avoids base64 overhead).
  getTextureBinary: (handle: ProjectHandle, texturePath: string) =>
    typedError<number[], CoreError>(
      __TAURI_INVOKE("get_texture_binary", { handle, texturePath }),
    ),
  // Save or update a `.mcmeta` animation descriptor alongside a texture.
  saveTextureMcmeta: (handle: ProjectHandle, texturePath: string, mcmetaJson: string) =>
    typedError<null, CoreError>(
      __TAURI_INVOKE("save_texture_mcmeta", { handle, texturePath, mcmetaJson }),
    ),
  saveTextures: (
    handle: ProjectHandle,
    textures: TextureSaveEntry[],
    options: {
      mode: SaveMode;
      targetPath?: string | null;
      namespace?: string | null;
    } | null,
  ) =>
    typedError<SaveTexturesResult, CoreError>(
      __TAURI_INVOKE("save_textures", { handle, textures, options }),
    ),
  /**
   *  Batch-save every dirty texture in one call. Each entry carries its own SaveOptions.
   *  This lets the UI flush all dirty textures to the same source in a single lock.
   */
  saveBatch: (
    handle: ProjectHandle,
    textures: TextureSaveEntry[],
    options: {
      mode: SaveMode;
      targetPath?: string | null;
      namespace?: string | null;
    } | null,
  ) =>
    typedError<SaveTexturesResult, CoreError>(
      __TAURI_INVOKE("save_batch", { handle, textures, options }),
    ),
  getSaveJournal: (handle: ProjectHandle) =>
    typedError<SaveJournalEntry[], CoreError>(
      __TAURI_INVOKE("get_save_journal", { handle }),
    ),
  rollbackLastSave: (handle: ProjectHandle) =>
    typedError<null, CoreError>(__TAURI_INVOKE("rollback_last_save", { handle })),
  listProjectBackups: (handle: ProjectHandle) =>
    typedError<BackupInfo[], CoreError>(
      __TAURI_INVOKE("list_project_backups", { handle }),
    ),
  restoreProjectBackup: (handle: ProjectHandle, backupPath: string) =>
    typedError<null, CoreError>(
      __TAURI_INVOKE("restore_project_backup", { handle, backupPath }),
    ),
  createProjectBackup: (handle: ProjectHandle) =>
    typedError<BackupInfo, CoreError>(
      __TAURI_INVOKE("create_project_backup", { handle }),
    ),
  restoreProjectBackupById: (handle: ProjectHandle, backupId: string) =>
    typedError<null, CoreError>(
      __TAURI_INVOKE("restore_project_backup_by_id", { handle, backupId }),
    ),
  listVariants: (handle: ProjectHandle, assetPath: string) =>
    typedError<VariantKey[], CoreError>(
      __TAURI_INVOKE("list_variants", { handle, assetPath }),
    ),
  modelsForTexture: (handle: ProjectHandle, assetPath: string) =>
    typedError<ModelRefInfo[], CoreError>(
      __TAURI_INVOKE("models_for_texture", { handle, assetPath }),
    ),
  resolveRenderable: (
    handle: ProjectHandle,
    assetPath: string,
    variantKey: string | null,
    linkedModelPath: string | null,
  ) =>
    typedError<RenderableModel, CoreError>(
      __TAURI_INVOKE("resolve_renderable", {
        handle,
        assetPath,
        variantKey,
        linkedModelPath,
      }),
    ),
  readRecentLogs: (maxLines: number | null) =>
    typedError<LogTailResponse, string>(__TAURI_INVOKE("read_recent_logs", { maxLines })),
  revealLogDir: () => typedError<null, CoreError>(__TAURI_INVOKE("reveal_log_dir")),
};

/* Types */
export type AppInfo = {
  name: string;
  version: string;
  identifier: string;
  target: string;
  profile: string;
  logDir: string | null;
};

export type AssetDetails = {
  id: string;
  kind: AssetKind;
  path: string;
  namespace: string;
  displayName: string;
  packFormat: number | null;
  textureWidth: number | null;
  textureHeight: number | null;
  linkedModels: ModelRefInfo[];
  relationships: RelationshipNode[];
  warnings: AssetWarning[];
};

export type AssetEntry = {
  id: string;
  kind: AssetKind;
  namespace: string;
  // Path inside the source (zip entry or relative file path), forward slashes.
  path: string;
  displayName: string;
  // Number of models referencing this texture (textures only).
  linkedModelCount?: number | null;
};

export type AssetFacets = {
  byKind: FacetCount[];
  byNamespace: FacetCount[];
};

export type AssetFilter = {
  kind: AssetKind | null;
  namespace: string | null;
  search: string | null;
  fuzzy?: boolean;
};

export type AssetKind =
  | "texture"
  | "textureMeta"
  | "blockModel"
  | "itemModel"
  | "blockstate"
  | "packMeta"
  | "lang"
  | "sound"
  | "other";

export type AssetPage = {
  entries: AssetEntry[];
  total: number;
};

export type AssetWarning = {
  code: string;
  message: string;
};

export type BackupInfo = {
  // Stable opaque identifier derived from the backup path (SHA-256 hex prefix).
  id: string;
  path: string;
  createdAt: number;
  label: string;
  kind: string;
};

export type CatalogCategory =
  | "building"
  | "nature"
  | "redstone"
  | "decoration"
  | "tools"
  | "food"
  | "misc";

export type CatalogEntry = {
  // Stable id, e.g. `minecraft:stone`
  id: string;
  namespace: string;
  displayName: string;
  kind: CatalogEntryKind;
  // blockstate path or item/block model path (legacy; prefer studio_model_path)
  sourcePath: string;
  resolveKind: CatalogResolveKind;
  defaultVariantKey?: string | null;
  category: CatalogCategory;
  searchTokens: string[];
  texturePaths: string[];
  iconKey: string;
  aliases?: string[];
  // `minecraft:stone` when this entry represents a block
  blockId?: string | null;
  // `minecraft:diamond_sword` when this entry represents an item
  itemId?: string | null;
  // Asset path used for inventory icon resolve
  iconModelPath?: string | null;
  // Asset path used for 3D studio viewport
  studioModelPath: string;
  // All blockstate variant keys for UI picker
  variantKeys?: string[];
  presentation: CatalogPresentation;
};

export type CatalogEntryKind = "block" | "item";

export type CatalogFacets = {
  byCategory: FacetCount[];
};

export type CatalogFilter = {
  category: CatalogCategory | null;
  namespace: string | null;
  search: string | null;
  fuzzy?: boolean;
};

export type CatalogPage = {
  entries: CatalogEntry[];
  total: number;
};

export type CatalogPresentation = "block" | "item" | "tool" | "food";

export type CatalogResolveKind = "blockstate" | "model" | "texture";

export type CoreError =
  | ({ Archive: string } & {
      AssetNotFound?: never;
      Internal?: never;
      InvalidInput?: never;
      InvalidPack?: never;
      ModelNotFound?: never;
      Unavailable?: never;
    })
  | "Cancelled"
  | "ProjectNotFound"
  | ({ AssetNotFound: string } & {
      Archive?: never;
      Internal?: never;
      InvalidInput?: never;
      InvalidPack?: never;
      ModelNotFound?: never;
      Unavailable?: never;
    })
  | ({ ModelNotFound: string } & {
      Archive?: never;
      AssetNotFound?: never;
      Internal?: never;
      InvalidInput?: never;
      InvalidPack?: never;
      Unavailable?: never;
    })
  | ({ InvalidPack: string } & {
      Archive?: never;
      AssetNotFound?: never;
      Internal?: never;
      InvalidInput?: never;
      ModelNotFound?: never;
      Unavailable?: never;
    })
  | ({ InvalidInput: string } & {
      Archive?: never;
      AssetNotFound?: never;
      Internal?: never;
      InvalidPack?: never;
      ModelNotFound?: never;
      Unavailable?: never;
    })
  | ({ Unavailable: string } & {
      Archive?: never;
      AssetNotFound?: never;
      Internal?: never;
      InvalidInput?: never;
      InvalidPack?: never;
      ModelNotFound?: never;
    })
  | ({ Internal: string } & {
      Archive?: never;
      AssetNotFound?: never;
      InvalidInput?: never;
      InvalidPack?: never;
      ModelNotFound?: never;
      Unavailable?: never;
    });

export type DisplayTransform = {
  rotation: [number, number, number];
  translation: [number, number, number];
  scale: [number, number, number];
};

export type ElementRotation = {
  origin: [number, number, number];
  axis: string;
  angle: number;
  rescale: boolean;
};

export type FacetCount = {
  key: string;
  count: number;
};

export type IndexEvent =
  | { type: "started"; total: number }
  | { type: "progress"; scanned: number; total: number; stage: string }
  | { type: "asset"; entry: AssetEntry }
  | { type: "warning"; path: string; reason: string }
  | { type: "done"; durationMs: number; fromCache: boolean };

export type LogTailResponse = {
  logDir: string | null;
  file: string | null;
  lines: string[];
};

export type ModelRefInfo = {
  modelId: string;
  path: string;
  kind: string;
  label: string;
};

export type ModelRotation = {
  x: number;
  y: number;
  z: number;
  uvlock: boolean;
};

export type ReindexResult = {
  assetCount: number;
  catalogCount: number;
};

export type OpenSourceResult = {
  handle: ProjectHandle;
  sourcePath: string;
  sourceKind: SourceKind;
  entryCount: number;
  fromCache: boolean;
  catalogFromCache: boolean;
  catalogEntryCount: number;
  packFormat: number | null;
  catalogLanguage: string;
};

export type PageReq = {
  offset: number;
  limit: number;
};

export type ProjectHandle = {
  id: number;
};

export type RelationshipNode = {
  id: string;
  label: string;
  kind: string;
  path: string;
  children: RelationshipNode[];
};

export type RenderCuboid = {
  from: [number, number, number];
  to: [number, number, number];
  rotation: ElementRotation | null;
  faces: RenderFace[];
  shade: boolean;
};

export type RenderFace = {
  direction: string;
  uv: [number, number, number, number];
  texture: string;
  rotation: number;
  tintindex: number;
  cullface: string | null;
};

export type RenderableKind = "block" | "itemGenerated" | "itemModel" | "multipart";

export type RenderableModel = {
  kind: RenderableKind;
  cuboids: RenderCuboid[];
  textureRefs: { [key in string]: string };
  textureMeta: { [key in string]: TextureMetaInfo };
  modelRotation: ModelRotation;
  display: { [key in string]: DisplayTransform };
  ambientOcclusion: boolean;
  modelId: string;
};

export type SaveJournalEntry = {
  timestamp: number;
  mode: SaveMode;
  originalPaths: string[];
  savedPaths: string[];
  backupPath: string | null;
};

export type SaveMode = "overwrite" | "exportFolder" | "rename" | "namespace";

export type SaveOptions = {
  mode: SaveMode;
  targetPath?: string | null;
  namespace?: string | null;
};

export type SaveTexturesResult = {
  savedCount: number;
  savedPaths: string[];
  originalPaths: string[];
  backupPath: string | null;
};

export type SourceKind = "jar" | "folder";

export type StudioResolveContext =
  | "icon"
  // World-placed block model (no item display transform).
  | "placed"
  // @deprecated alias for `Placed`
  | "studio";

export type TextureAnimationMeta = {
  frametime: number;
  interpolate: boolean;
  frameWidth: number;
  frameHeight: number;
  frames: number[];
};

export type TextureMetaInfo = {
  width: number;
  height: number;
  animation: TextureAnimationMeta | null;
};

export type TexturePreview = {
  width: number;
  height: number;
  pngBase64: string;
};

export type TexturePreviewBatch = {
  path: string;
  preview: TexturePreview | null;
};

export type TextureSaveEntry = {
  path: string;
  pngBase64: string;
  targetPath?: string | null;
};

export type VariantKey = {
  key: string;
  model: string;
  x: number;
  y: number;
  z: number;
  uvlock: boolean;
  weight?: number | null;
};

/* Tauri Specta runtime */
async function typedError<T, E>(
  result: Promise<T>,
): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
  try {
    return { status: "ok", data: await result };
  } catch (e) {
    if (e instanceof Error) throw e;
    return { status: "error", error: e as any };
  }
}
