// AUTO-GENERATED by export_types.rs — do not edit manually.
// Run:  cd src-tauri && cargo run --bin export_types// AUTO-GENERATED by export_types.rs — do not edit manually.
// Run:  cd src-tauri && cargo run --bin export_types
// This file has been generated by Specta. DO NOT EDIT.

export type AppInfo = {
  name: string;
  version: string;
  identifier: string;
  target: string;
  profile: string;
  logDir: string | null;
};

export type AssetEntry = {
  id: string;
  kind: AssetKind;
  namespace: string;
  /**
   * Path inside the source (zip entry or relative file path), forward slashes.
   */
  path: string;
  displayName: string;
};

export type AssetFacets = { byKind: FacetCount[]; byNamespace: FacetCount[] };

export type AssetFilter = {
  kind: AssetKind | null;
  namespace: string | null;
  search: string | null;
  fuzzy?: boolean;
};

export type AssetKind =
  | "texture"
  | "textureMeta"
  | "blockModel"
  | "itemModel"
  | "blockstate"
  | "packMeta"
  | "lang"
  | "sound"
  | "other";

export type AssetPage = { entries: AssetEntry[]; total: number };

export type BackupInfo = {
  /**
   * Stable opaque identifier derived from the backup path (SHA-256 hex prefix).
   */
  id: string;
  path: string;
  createdAt: number;
  label: string;
  kind: string;
};

export type DisplayTransform = {
  rotation: [number, number, number];
  translation: [number, number, number];
  scale: [number, number, number];
};

export type ElementRotation = {
  origin: [number, number, number];
  axis: string;
  angle: number;
  rescale: boolean;
};

export type FacetCount = { key: string; count: number };

export type IndexEvent =
  | { type: "started"; total: number }
  | { type: "progress"; scanned: number; total: number; stage: string }
  | { type: "asset"; entry: AssetEntry }
  | { type: "warning"; path: string; reason: string }
  | { type: "done"; duration_ms: number; from_cache: boolean };

export type ModelRefInfo = { modelId: string; path: string; kind: string; label: string };

export type ModelRotation = { x: number; y: number; z: number; uvlock: boolean };

export type OpenSourceResult = {
  handle: ProjectHandle;
  sourcePath: string;
  sourceKind: SourceKind;
  entryCount: number;
  fromCache: boolean;
  packFormat: number | null;
};

export type PageReq = { offset: number; limit: number };

export type ProjectHandle = { id: number };

export type RenderCuboid = {
  from: [number, number, number];
  to: [number, number, number];
  rotation: ElementRotation | null;
  faces: RenderFace[];
  shade: boolean;
};

export type RenderFace = {
  direction: string;
  uv: [number, number, number, number];
  texture: string;
  rotation: number;
  tintindex: number;
  cullface: string | null;
};

export type RenderableKind = "block" | "itemGenerated" | "itemModel" | "multipart";

export type RenderableModel = {
  kind: RenderableKind;
  cuboids: RenderCuboid[];
  textureRefs: Partial<{ [key in string]: string }>;
  textureMeta: Partial<{ [key in string]: TextureMetaInfo }>;
  modelRotation: ModelRotation;
  display: Partial<{ [key in string]: DisplayTransform }>;
  ambientOcclusion: boolean;
  modelId: string;
};

export type SaveJournalEntry = {
  timestamp: number;
  mode: SaveMode;
  originalPaths: string[];
  savedPaths: string[];
  backupPath: string | null;
};

export type SaveMode = "overwrite" | "exportFolder" | "rename" | "namespace";

export type SaveOptions = {
  mode: SaveMode;
  targetPath?: string | null;
  namespace?: string | null;
};

export type SaveTexturesResult = {
  savedCount: number;
  savedPaths: string[];
  originalPaths: string[];
  backupPath: string | null;
};

export type SourceKind = "jar" | "folder";

export type TextureAnimationMeta = {
  frametime: number;
  interpolate: boolean;
  frameWidth: number;
  frameHeight: number;
  frames: number[];
};

export type TextureMetaInfo = {
  width: number;
  height: number;
  animation: TextureAnimationMeta | null;
};

export type TexturePreview = { width: number; height: number; pngBase64: string };

export type TextureSaveEntry = {
  path: string;
  pngBase64: string;
  targetPath?: string | null;
};

export type VariantKey = {
  key: string;
  model: string;
  x: number;
  y: number;
  z: number;
  uvlock: boolean;
};
