import type { Channel } from "@tauri-apps/api/core";

import { commands } from "./bindings";
import type {
  AssetDetails,
  AssetEntry,
  AssetFacets,
  AssetFilter,
  AssetPage,
  BackupInfo,
  CatalogEntry,
  CatalogFacets,
  CatalogFilter,
  CatalogPage,
  CoreError,
  IndexEvent,
  LogTailResponse,
  ModelRefInfo,
  OpenSourceResult,
  RenderableModel,
  SaveJournalEntry,
  SaveOptions,
  SaveTexturesResult,
  TexturePreview,
  TexturePreviewBatch,
  TextureSaveEntry,
  VariantKey,
} from "./bindings";
import { IpcError } from "./errors";
import type { CoreErrorPayload } from "./types";

type SpectaResult<T> = { status: "ok"; data: T } | { status: "error"; error: unknown };

function coreErrorToPayload(error: CoreError): CoreErrorPayload {
  if (error === "Cancelled") return { code: "cancelled", message: "operation cancelled" };
  if (error === "ProjectNotFound")
    return { code: "projectNotFound", message: "project not found" };
  if ("Archive" in error && error.Archive !== undefined) {
    return { code: "archive", message: error.Archive };
  }
  if ("AssetNotFound" in error && error.AssetNotFound !== undefined) {
    return { code: "assetNotFound", message: error.AssetNotFound };
  }
  if ("ModelNotFound" in error && error.ModelNotFound !== undefined) {
    return { code: "modelNotFound", message: error.ModelNotFound };
  }
  if ("InvalidPack" in error && error.InvalidPack !== undefined) {
    return { code: "invalidPack", message: error.InvalidPack };
  }
  if ("InvalidInput" in error && error.InvalidInput !== undefined) {
    return { code: "invalidInput", message: error.InvalidInput };
  }
  if ("Unavailable" in error && error.Unavailable !== undefined) {
    return { code: "unavailable", message: error.Unavailable };
  }
  if ("Internal" in error && error.Internal !== undefined) {
    return { code: "internal", message: error.Internal };
  }
  return { code: "internal", message: "unknown error" };
}

async function unwrap<T>(result: Promise<T | SpectaResult<unknown>>): Promise<T> {
  const value = await result;
  if (value && typeof value === "object" && "status" in value) {
    const r = value as SpectaResult<unknown>;
    if (r.status === "error") {
      if (typeof r.error === "string") {
        throw new IpcError({ code: "internal", message: r.error });
      }
      throw new IpcError(coreErrorToPayload(r.error as CoreError));
    }
    return r.data as T;
  }
  return value as T;
}

function toBindingFilter(filter: AssetFilter): AssetFilter {
  return {
    kind: filter.kind ?? null,
    namespace: filter.namespace ?? null,
    search: filter.search ?? null,
    fuzzy: filter.fuzzy,
  };
}

function toBindingSaveOptions(options?: SaveOptions) {
  if (!options) return null;
  return {
    mode: options.mode,
    targetPath: options.targetPath ?? null,
    namespace: options.namespace ?? null,
  };
}

function toBindingCatalogFilter(filter: CatalogFilter): CatalogFilter {
  return {
    category: filter.category ?? null,
    namespace: filter.namespace ?? null,
    search: filter.search ?? null,
    fuzzy: filter.fuzzy,
  };
}

/** Typed invoke wrappers generated by tauri-specta (`src/ipc/bindings.ts`). */
export const spectaCommands = {
  getAppInfo: () => commands.getAppInfo(),
  ping: () => commands.ping(),
  getSamplePackPath: () => unwrap<string>(commands.getSamplePackPath()),
  openSource: (path: string, onEvent: Channel<IndexEvent>) =>
    unwrap<OpenSourceResult>(commands.openSource(path, onEvent)),
  reindexProject: (
    handle: Parameters<typeof commands.reindexProject>[0],
    onEvent: Channel<IndexEvent>,
    changedPaths?: string[] | null,
  ) => unwrap<number>(commands.reindexProject(handle, onEvent, changedPaths ?? null)),
  invalidateProjectIndex: (
    handle: Parameters<typeof commands.invalidateProjectIndex>[0],
  ) => unwrap<void>(commands.invalidateProjectIndex(handle)),
  closeSource: (handle: Parameters<typeof commands.closeSource>[0]) =>
    unwrap<void>(commands.closeSource(handle)),
  cancelIndex: (handle: Parameters<typeof commands.cancelIndex>[0]) =>
    unwrap<void>(commands.cancelIndex(handle)),
  queryAssets: (
    handle: Parameters<typeof commands.queryAssets>[0],
    filter: AssetFilter,
    page: Parameters<typeof commands.queryAssets>[2],
  ) => unwrap<AssetPage>(commands.queryAssets(handle, toBindingFilter(filter), page)),
  getAssetFacets: (handle: Parameters<typeof commands.getAssetFacets>[0]) =>
    unwrap<AssetFacets>(commands.getAssetFacets(handle)),
  queryCatalog: (
    handle: Parameters<typeof commands.queryCatalog>[0],
    filter: CatalogFilter,
    page: Parameters<typeof commands.queryCatalog>[2],
  ) =>
    unwrap<CatalogPage>(
      commands.queryCatalog(handle, toBindingCatalogFilter(filter), page),
    ),
  getCatalogEntry: (
    handle: Parameters<typeof commands.getCatalogEntry>[0],
    entryId: string,
  ) => unwrap<CatalogEntry>(commands.getCatalogEntry(handle, entryId)),
  getCatalogFacets: (handle: Parameters<typeof commands.getCatalogFacets>[0]) =>
    unwrap<CatalogFacets>(commands.getCatalogFacets(handle)),
  resolveCatalogEntry: (
    handle: Parameters<typeof commands.resolveCatalogEntry>[0],
    entryId: string,
  ) => unwrap<RenderableModel>(commands.resolveCatalogEntry(handle, entryId)),
  getAssetEntry: (
    handle: Parameters<typeof commands.getAssetEntry>[0],
    assetId: string,
  ) => unwrap<AssetEntry>(commands.getAssetEntry(handle, assetId)),
  getAssetDetails: (
    handle: Parameters<typeof commands.getAssetDetails>[0],
    assetId: string,
  ) => unwrap<AssetDetails>(commands.getAssetDetails(handle, assetId)),
  getTexturePreview: (
    handle: Parameters<typeof commands.getTexturePreview>[0],
    assetPath: string,
    maxSize?: number | null,
  ) =>
    unwrap<TexturePreview>(
      commands.getTexturePreview(handle, assetPath, maxSize ?? null),
    ),
  getTexturePreviewsBatch: (
    handle: Parameters<typeof commands.getTexturePreviewsBatch>[0],
    assetPaths: string[],
    maxSize?: number | null,
  ) =>
    unwrap<TexturePreviewBatch[]>(
      commands.getTexturePreviewsBatch(handle, assetPaths, maxSize ?? null),
    ),
  revealAssetInFolder: (...args: Parameters<typeof commands.revealAssetInFolder>) =>
    unwrap<void>(commands.revealAssetInFolder(...args)),
  getTexture: (...args: Parameters<typeof commands.getTexture>) =>
    unwrap<TexturePreview>(commands.getTexture(...args)),
  getTextureBinary: async (...args: Parameters<typeof commands.getTextureBinary>) => {
    const bytes = await unwrap<number[]>(commands.getTextureBinary(...args));
    return new Uint8Array(bytes);
  },
  saveTextureMcmeta: (...args: Parameters<typeof commands.saveTextureMcmeta>) =>
    unwrap<void>(commands.saveTextureMcmeta(...args)),
  saveTextures: (
    handle: Parameters<typeof commands.saveTextures>[0],
    textures: TextureSaveEntry[],
    options?: SaveOptions,
  ) =>
    unwrap<SaveTexturesResult>(
      commands.saveTextures(handle, textures, toBindingSaveOptions(options)),
    ),
  saveBatch: (
    handle: Parameters<typeof commands.saveBatch>[0],
    textures: TextureSaveEntry[],
    options?: SaveOptions,
  ) =>
    unwrap<SaveTexturesResult>(
      commands.saveBatch(handle, textures, toBindingSaveOptions(options)),
    ),
  getSaveJournal: (handle: Parameters<typeof commands.getSaveJournal>[0]) =>
    unwrap<SaveJournalEntry[]>(commands.getSaveJournal(handle)),
  rollbackLastSave: (handle: Parameters<typeof commands.rollbackLastSave>[0]) =>
    unwrap<void>(commands.rollbackLastSave(handle)),
  listProjectBackups: (handle: Parameters<typeof commands.listProjectBackups>[0]) =>
    unwrap<BackupInfo[]>(commands.listProjectBackups(handle)),
  restoreProjectBackup: (...args: Parameters<typeof commands.restoreProjectBackup>) =>
    unwrap<void>(commands.restoreProjectBackup(...args)),
  createProjectBackup: (handle: Parameters<typeof commands.createProjectBackup>[0]) =>
    unwrap<BackupInfo>(commands.createProjectBackup(handle)),
  restoreProjectBackupById: (
    ...args: Parameters<typeof commands.restoreProjectBackupById>
  ) => unwrap<void>(commands.restoreProjectBackupById(...args)),
  listVariants: (...args: Parameters<typeof commands.listVariants>) =>
    unwrap<VariantKey[]>(commands.listVariants(...args)),
  modelsForTexture: (...args: Parameters<typeof commands.modelsForTexture>) =>
    unwrap<ModelRefInfo[]>(commands.modelsForTexture(...args)),
  resolveRenderable: (
    handle: Parameters<typeof commands.resolveRenderable>[0],
    assetPath: string,
    variantKey?: string | null,
    linkedModelPath?: string | null,
  ) =>
    unwrap<RenderableModel>(
      commands.resolveRenderable(
        handle,
        assetPath,
        variantKey ?? null,
        linkedModelPath ?? null,
      ),
    ),
  readRecentLogs: (maxLines?: number | null) =>
    unwrap<LogTailResponse>(commands.readRecentLogs(maxLines ?? null)),
  revealLogDir: () => unwrap<void>(commands.revealLogDir()),
};
