use specta_typescript::Typescript;
use tauri_specta::{collect_commands, Builder};

/// Shared tauri-specta builder — single source for invoke handler + TS export.
pub fn builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(collect_commands![
        get_app_info,
        ping,
        get_sample_pack_path,
        open_source,
        reindex_project,
        invalidate_project_index,
        close_source,
        cancel_index,
        query_assets,
        get_asset_facets,
        query_catalog,
        get_catalog_entry,
        get_catalog_facets,
        resolve_catalog_entry,
        get_asset_entry,
        get_asset_details,
        get_texture_previews_batch,
        reveal_asset_in_folder,
        get_texture_preview,
        get_texture,
        get_texture_binary,
        save_texture_mcmeta,
        save_textures,
        save_batch,
        get_save_journal,
        rollback_last_save,
        list_project_backups,
        restore_project_backup,
        create_project_backup,
        restore_project_backup_by_id,
        list_variants,
        models_for_texture,
        resolve_renderable,
        read_recent_logs,
        reveal_log_dir,
    ])
}

pub fn export_typescript(path: &str) {
    builder()
        .export(
            Typescript::default().header(
                "// AUTO-GENERATED by export_bindings — do not edit manually.\n\
                 // Run: npm run gen:types",
            ),
            path,
        )
        .expect("failed to export tauri-specta bindings");
}

use std::collections::{HashMap, HashSet};
use std::sync::Mutex;

use tauri::{Manager, State};
use tauri_plugin_opener::OpenerExt;

use crate::compile::{compile_multipart_renderable, compile_renderable, compile_texture_preview, list_variant_keys};
use crate::dto::{
    AppInfo, AssetDetails, AssetFacets, AssetFilter, AssetPage, AssetKind, BackupInfo, CatalogFacets,
    IndexEvent,
    ModelRefInfo, OpenSourceResult, PageReq, ProjectHandle, RenderableModel, SaveJournalEntry,
    SaveMode, SaveOptions, SaveTexturesResult, TexturePreview, TexturePreviewBatch,
    TextureSaveEntry, VariantKey,
};
use crate::error::{CoreError, CoreResult};
use crate::image::{decode_texture_preview, encode_texture_full};
use crate::index::{invalidate_index, patch_entries_for_paths, run_index, source_fingerprint, texture_index};
use crate::save::restore_backup_by_id;
use crate::model::multipart::{parse_variant_state, resolve_multipart_models};
use crate::model::normalize::{read_pack_info, PackInfo};
use crate::model::types::{
    blockstate_id_from_asset_path, model_id_from_asset_path, normalize_model_ref,
    texture_stem_from_entry_path,
};
use crate::resolve::{collect_variant_models, find_models_for_texture, ModelRegistry};
use crate::save::{
    create_backup, list_backups, prepare_textures, restore_backup_from_known_path, save_prepared_textures,
};
use crate::source::open_source as load_source;
use crate::source::safe_join_under_root;
use crate::state::SharedState;

fn pack_for_project(project: &crate::state::Project) -> PackInfo {
    PackInfo {
        pack_format: project.pack_format,
    }
}

fn rebuild_texture_model_index(project: &mut crate::state::Project) {
    let pack = pack_for_project(project);
    let entries = project.entries.clone();
    let mut cache = project.model_cache.lock().expect("cache poisoned");
    let mut registry = ModelRegistry::new(project.source.as_ref(), &mut cache, pack);
    project.texture_model_index =
        texture_index::build_texture_model_index(&mut registry, &entries);
    drop(cache);
    apply_texture_link_counts(project);
}

fn apply_texture_link_counts(project: &mut crate::state::Project) {
    let index = project.texture_model_index.clone();
    for entry in &mut project.entries {
        if entry.kind == AssetKind::Texture {
            let count =
                texture_index::models_for_texture_path(&index, &entry.path).len() as u32;
            entry.linked_model_count = Some(count);
        }
    }
}

fn project_for_handle(
    app: &crate::state::AppState,
    handle: ProjectHandle,
) -> CoreResult<&crate::state::Project> {
    app.projects
        .get(&handle.id)
        .ok_or(CoreError::ProjectNotFound)
}

fn project_for_handle_mut(
    app: &mut crate::state::AppState,
    handle: ProjectHandle,
) -> CoreResult<&mut crate::state::Project> {
    app.projects
        .get_mut(&handle.id)
        .ok_or(CoreError::ProjectNotFound)
}

fn refresh_index_cache(
    db: &sled::Db,
    old_fingerprint: &str,
    new_fingerprint: &str,
    entries: &[crate::dto::AssetEntry],
) -> CoreResult<()> {
    if old_fingerprint != new_fingerprint {
        let _ = invalidate_index(db, old_fingerprint);
        let _ = crate::catalog::invalidate_project_catalog_cache(db, old_fingerprint);
    }
    let encoded = serde_json::to_vec(entries)
        .map_err(|e| CoreError::Internal(format!("cache encode failed: {e}")))?;
    db.insert(
        crate::index::cache_key_for(new_fingerprint).as_bytes(),
        encoded,
    )?;
    Ok(())
}

fn indexed_texture_paths(project: &crate::state::Project) -> HashSet<&str> {
    project
        .entries
        .iter()
        .filter(|entry| entry.kind == AssetKind::Texture)
        .map(|entry| entry.path.as_str())
        .collect()
}

fn invalidate_jar_cache_if_needed(source_kind: crate::dto::SourceKind, source_path: &std::path::Path) {
    if source_kind == crate::dto::SourceKind::Jar {
        if let Ok(jar) = crate::source::JarSource::new(source_path) {
            jar.invalidate_cache();
        }
    }
}

fn refresh_project_for_paths(
    app: &mut crate::state::AppState,
    db: &sled::Db,
    handle: ProjectHandle,
    changed_paths: &[String],
) -> CoreResult<(crate::dto::SourceKind, std::path::PathBuf)> {
    let project = project_for_handle_mut(app, handle)?;
    let source_path = project.source_path.clone();
    let source_kind = project.source_kind;
    project.source = load_source(&source_path)?;
    let old_fp = project.fingerprint.clone();
    let new_fp = source_fingerprint(&project.source_path)?;
    let _ = patch_entries_for_paths(
        &mut project.entries,
        project.source.as_ref(),
        changed_paths,
        None,
    );
    project.fingerprint = new_fp.clone();
    let entries_snapshot = project.entries.clone();
    if let Ok(mut cache) = project.model_cache.lock() {
        cache.clear();
    }
    rebuild_texture_model_index(project);
    let _ = refresh_index_cache(db, &old_fp, &new_fp, &entries_snapshot);
    let _ = crate::catalog::invalidate_project_catalog_cache(db, &new_fp);
    let _ = crate::catalog::build_project_catalog(project, db);
    Ok((source_kind, source_path))
}

#[tauri::command]
#[specta::specta]
pub fn get_app_info(state: State<'_, SharedState>) -> AppInfo {
    state.read().app_info()
}

#[tauri::command]
#[specta::specta]
pub fn ping() -> &'static str {
    "pong"
}

#[tauri::command]
#[specta::specta]
pub fn get_sample_pack_path() -> Result<String, String> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../assets/sample");
    if !path.exists() {
        return Err("Sample pack directory not found".into());
    }
    path.canonicalize()
        .map(|p| p.to_string_lossy().into_owned())
        .map_err(|e| e.to_string())
}

#[tauri::command]
#[specta::specta]
pub async fn open_source(
    path: String,
    on_event: tauri::ipc::Channel<IndexEvent>,
    state: State<'_, SharedState>,
    app_handle: tauri::AppHandle,
) -> CoreResult<OpenSourceResult> {
    let source_path = std::path::PathBuf::from(&path);
    let source = load_source(&source_path)?;
    let source_kind = source.source_kind();
    let fingerprint = source_fingerprint(source.source_path())?;

    let (handle_id, cancel, db) = {
        let mut app = state.write();
        let handle = app.alloc_handle();
        let cancel = app.register_cancel(handle.id);
        let db = app.db.clone();
        (handle.id, cancel, db)
    };

    let (entries, from_cache) =
        run_index(source.as_ref(), &db, &fingerprint, &cancel, &on_event)?;

    let pack_info = read_pack_info(source.as_ref());

    let (result, watcher_shared) = {
        let mut app = state.write();
        app.clear_cancel(handle_id);
        app.projects.insert(
            handle_id,
            crate::state::Project {
                source_path: source_path.clone(),
                source_kind,
                fingerprint,
                pack_format: pack_info.pack_format,
                entries: entries.clone(),
                catalog: Vec::new(),
                source,
                model_cache: Mutex::new(HashMap::new()),
                texture_model_index: HashMap::new(),
                save_journal: Vec::new(),
            },
        );
        if let Some(project) = app.projects.get_mut(&handle_id) {
            rebuild_texture_model_index(project);
            let _ = crate::catalog::build_project_catalog(project, &db);
        }
        let res = OpenSourceResult {
            handle: ProjectHandle { id: handle_id },
            source_path: path,
            source_kind,
            entry_count: entries.len() as u64,
            from_cache,
            pack_format: pack_info.pack_format,
        };
        (res, std::sync::Arc::clone(&app.watcher))
    };

    // Install file-system watcher for external change detection
    crate::watcher::install_watcher(app_handle, handle_id, source_path, &watcher_shared);

    Ok(result)
}

#[tauri::command]
#[specta::specta]
pub async fn reindex_project(
    handle: ProjectHandle,
    on_event: tauri::ipc::Channel<IndexEvent>,
    changed_paths: Option<Vec<String>>,
    state: State<'_, SharedState>,
) -> CoreResult<u64> {
    let (old_fingerprint, cancel, db, source_path, source_kind) = {
        let app = state.read();
        let project = app.projects.get(&handle.id).ok_or(CoreError::ProjectNotFound)?;
        let cancel = app
            .cancel_flags
            .get(&handle.id)
            .cloned()
            .unwrap_or_else(|| std::sync::Arc::new(std::sync::atomic::AtomicBool::new(false)));
        (
            project.fingerprint.clone(),
            cancel,
            app.db.clone(),
            project.source_path.clone(),
            project.source_kind,
        )
    };

    let source = load_source(&source_path)?;
    let new_fingerprint = source_fingerprint(&source_path)?;

    let entries = if let Some(paths) = changed_paths.filter(|p| !p.is_empty()) {
        let mut app = state.write();
        let project = app.projects.get_mut(&handle.id).ok_or(CoreError::ProjectNotFound)?;
        patch_entries_for_paths(&mut project.entries, source.as_ref(), &paths, Some(&on_event))?;
        if let Ok(mut cache) = project.model_cache.lock() {
            cache.clear();
        }
        project.fingerprint = new_fingerprint.clone();
        project.source = source;
        refresh_index_cache(&db, &old_fingerprint, &new_fingerprint, &project.entries)?;
        rebuild_texture_model_index(project);
        let _ = crate::catalog::invalidate_project_catalog_cache(&db, &new_fingerprint);
        let _ = crate::catalog::build_project_catalog(project, &db);
        project.entries.len() as u64
    } else {
        if old_fingerprint != new_fingerprint {
            let _ = invalidate_index(&db, &old_fingerprint);
            let _ = crate::catalog::invalidate_project_catalog_cache(&db, &old_fingerprint);
        }
        let (entries, _) =
            run_index(source.as_ref(), &db, &new_fingerprint, &cancel, &on_event)?;

        let mut app = state.write();
        let project = app.projects.get_mut(&handle.id).ok_or(CoreError::ProjectNotFound)?;
        project.source = load_source(&source_path)?;
        project.entries = entries.clone();
        project.fingerprint = new_fingerprint;
        if let Ok(mut cache) = project.model_cache.lock() {
            cache.clear();
        }
        rebuild_texture_model_index(project);
        let _ = crate::catalog::build_project_catalog(project, &db);
        entries.len() as u64
    };

    if source_kind == crate::dto::SourceKind::Jar {
        if let Ok(jar) = crate::source::JarSource::new(&source_path) {
            jar.invalidate_cache();
        }
    }

    Ok(entries)
}

#[tauri::command]
#[specta::specta]
pub fn invalidate_project_index(handle: ProjectHandle, state: State<'_, SharedState>) -> CoreResult<()> {
    let app = state.read();
    let project = app.projects.get(&handle.id).ok_or(CoreError::ProjectNotFound)?;
    invalidate_index(&app.db, &project.fingerprint)?;
    crate::catalog::invalidate_project_catalog_cache(&app.db, &project.fingerprint)
}

#[tauri::command]
#[specta::specta]
pub fn close_source(handle: ProjectHandle, state: State<'_, SharedState>) -> CoreResult<()> {
    let mut app = state.write();
    app.cancel_index(handle.id);
    app.projects.remove(&handle.id);
    app.clear_cancel(handle.id);
    crate::watcher::stop_watcher(handle.id, &std::sync::Arc::clone(&app.watcher));
    Ok(())
}

#[tauri::command]
#[specta::specta]
pub fn cancel_index(handle: ProjectHandle, state: State<'_, SharedState>) -> CoreResult<()> {
    state.read().cancel_index(handle.id);
    Ok(())
}

#[tauri::command]
#[specta::specta]
pub fn query_assets(
    handle: ProjectHandle,
    filter: AssetFilter,
    page: PageReq,
    state: State<'_, SharedState>,
) -> CoreResult<AssetPage> {
    state
        .read()
        .query_assets(handle.id, filter, page)
        .ok_or(CoreError::ProjectNotFound)
}

#[tauri::command]
#[specta::specta]
pub fn get_asset_facets(
    handle: ProjectHandle,
    state: State<'_, SharedState>,
) -> CoreResult<AssetFacets> {
    state
        .read()
        .asset_facets(handle.id)
        .ok_or(CoreError::ProjectNotFound)
}

#[tauri::command]
#[specta::specta]
pub fn query_catalog(
    handle: ProjectHandle,
    filter: crate::dto::CatalogFilter,
    page: PageReq,
    state: State<'_, SharedState>,
) -> CoreResult<crate::dto::CatalogPage> {
    let app = state.read();
    let project = app.projects.get(&handle.id).ok_or(CoreError::ProjectNotFound)?;
    Ok(crate::catalog::query_catalog(&project.catalog, filter, page))
}

#[tauri::command]
#[specta::specta]
pub fn get_catalog_entry(
    handle: ProjectHandle,
    entry_id: String,
    state: State<'_, SharedState>,
) -> CoreResult<crate::dto::CatalogEntry> {
    let app = state.read();
    let project = app.projects.get(&handle.id).ok_or(CoreError::ProjectNotFound)?;
    crate::catalog::get_catalog_entry(&project.catalog, &entry_id)
        .cloned()
        .ok_or_else(|| CoreError::AssetNotFound(entry_id))
}

#[tauri::command]
#[specta::specta]
pub fn get_catalog_facets(
    handle: ProjectHandle,
    state: State<'_, SharedState>,
) -> CoreResult<CatalogFacets> {
    let app = state.read();
    let project = app.projects.get(&handle.id).ok_or(CoreError::ProjectNotFound)?;
    Ok(crate::catalog::catalog_facets(&project.catalog))
}

#[tauri::command]
#[specta::specta]
pub fn resolve_catalog_entry(
    handle: ProjectHandle,
    entry_id: String,
    state: State<'_, SharedState>,
) -> CoreResult<RenderableModel> {
    let (source_path, variant_key) = {
        let app = state.read();
        let project = app.projects.get(&handle.id).ok_or(CoreError::ProjectNotFound)?;
        let entry = crate::catalog::get_catalog_entry(&project.catalog, &entry_id)
            .ok_or_else(|| CoreError::AssetNotFound(entry_id.clone()))?;
        (entry.source_path.clone(), entry.default_variant_key.clone())
    };
    resolve_renderable(handle, source_path, variant_key, None, state)
}

#[tauri::command]
#[specta::specta]
pub fn get_asset_entry(
    handle: ProjectHandle,
    asset_id: String,
    state: State<'_, SharedState>,
) -> CoreResult<crate::dto::AssetEntry> {
    let app = state.read();
    let project = app.projects.get(&handle.id).ok_or(CoreError::ProjectNotFound)?;
    crate::asset_details::find_entry_by_id(project, &asset_id)
}

#[tauri::command]
#[specta::specta]
pub fn get_asset_details(
    handle: ProjectHandle,
    asset_id: String,
    state: State<'_, SharedState>,
) -> CoreResult<AssetDetails> {
    let app = state.read();
    let project = app.projects.get(&handle.id).ok_or(CoreError::ProjectNotFound)?;
    let entry = crate::asset_details::find_entry_by_id(project, &asset_id)?;
    crate::asset_details::build_asset_details(project, &entry)
}

#[tauri::command]
#[specta::specta]
pub fn get_texture_previews_batch(
    handle: ProjectHandle,
    asset_paths: Vec<String>,
    max_size: Option<u32>,
    state: State<'_, SharedState>,
) -> CoreResult<Vec<TexturePreviewBatch>> {
    let app = state.read();
    let project = app.projects.get(&handle.id).ok_or(CoreError::ProjectNotFound)?;
    let valid_textures = indexed_texture_paths(project);
    let size = max_size.unwrap_or(32);
    let mut out = Vec::with_capacity(asset_paths.len());
    for path in asset_paths {
        let preview = if valid_textures.contains(path.as_str()) {
            project
                .source
                .read(&path)
                .ok()
                .and_then(|bytes| decode_texture_preview(&bytes, size).ok())
        } else {
            None
        };
        out.push(TexturePreviewBatch { path, preview });
    }
    Ok(out)
}

#[tauri::command]
#[specta::specta]
pub fn reveal_asset_in_folder(
    handle: ProjectHandle,
    asset_path: String,
    app: tauri::AppHandle,
    state: State<'_, SharedState>,
) -> CoreResult<()> {
    let app_state = state.read();
    let project = app_state
        .projects
        .get(&handle.id)
        .ok_or(CoreError::ProjectNotFound)?;

    match project.source_kind {
        crate::dto::SourceKind::Folder => {
            let abs = safe_join_under_root(&project.source_path, &asset_path)?;
            let reveal = if abs.is_file() {
                abs
            } else {
                abs.parent()
                    .map(|p| p.to_path_buf())
                    .unwrap_or(project.source_path.clone())
            };
            app.opener()
                .open_path(reveal.to_string_lossy().to_string(), None::<&str>)
                .map_err(|e| CoreError::Internal(e.to_string()))?;
            Ok(())
        }
        crate::dto::SourceKind::Jar => {
            let parent = project
                .source_path
                .parent()
                .map(|p| p.to_path_buf())
                .unwrap_or_else(|| project.source_path.clone());
            app.opener()
                .open_path(parent.to_string_lossy().to_string(), None::<&str>)
                .map_err(|e| CoreError::Internal(e.to_string()))?;
            Ok(())
        }
    }
}

#[tauri::command]
#[specta::specta]
pub fn get_texture_preview(
    handle: ProjectHandle,
    asset_path: String,
    max_size: Option<u32>,
    state: State<'_, SharedState>,
) -> CoreResult<TexturePreview> {
    let app = state.read();
    let project = project_for_handle(&app, handle)?;

    let entry = project
        .entries
        .iter()
        .find(|e| e.path == asset_path)
        .ok_or_else(|| CoreError::AssetNotFound(asset_path.clone()))?;

    if entry.kind != AssetKind::Texture {
        return Err(CoreError::InvalidInput("not a texture asset".to_string()));
    }

    let bytes = project.source.read(&asset_path)?;
    decode_texture_preview(&bytes, max_size.unwrap_or(32))
}

#[tauri::command]
#[specta::specta]
pub fn get_texture(
    handle: ProjectHandle,
    texture_path: String,
    state: State<'_, SharedState>,
) -> CoreResult<TexturePreview> {
    let app = state.read();
    let project = project_for_handle(&app, handle)?;

    let bytes = project.source.read(&texture_path)?;
    encode_texture_full(&bytes)
}

/// Returns raw PNG bytes via Tauri binary IPC (avoids base64 overhead).
#[tauri::command]
#[specta::specta]
pub fn get_texture_binary(
    handle: ProjectHandle,
    texture_path: String,
    state: State<'_, SharedState>,
) -> CoreResult<Vec<u8>> {
    let app = state.read();
    let project = project_for_handle(&app, handle)?;

    let bytes = project.source.read(&texture_path)?;
    if !bytes.starts_with(b"\x89PNG") {
        return Err(CoreError::InvalidInput("not a valid PNG".to_string()));
    }
    Ok(bytes)
}

/// Save or update a `.mcmeta` animation descriptor alongside a texture.
#[tauri::command]
#[specta::specta]
pub fn save_texture_mcmeta(
    handle: ProjectHandle,
    texture_path: String,
    mcmeta_json: String,
    state: State<'_, SharedState>,
) -> CoreResult<()> {
    let app = state.read();
    let project = project_for_handle(&app, handle)?;

    // Validate JSON
    let _parsed: serde_json::Value = serde_json::from_str(&mcmeta_json)
        .map_err(|e| CoreError::Internal(format!("invalid mcmeta JSON: {e}")))?;

    let mcmeta_path = format!("{}.mcmeta", texture_path);
    let bytes = mcmeta_json.into_bytes();

    use crate::dto::SourceKind;
    match project.source_kind {
        SourceKind::Jar => {
            let mut replacements = HashMap::new();
            replacements.insert(mcmeta_path, bytes);
            crate::save::rebuild_jar_atomic(&project.source_path, &replacements)
        }
        SourceKind::Folder => {
            let abs = safe_join_under_root(&project.source_path, &mcmeta_path)?;
            if let Some(parent) = abs.parent() {
                std::fs::create_dir_all(parent)?;
            }
            std::fs::write(&abs, bytes)?;
            Ok(())
        }
    }
}

#[tauri::command]
#[specta::specta]
pub fn save_textures(
    handle: ProjectHandle,
    textures: Vec<TextureSaveEntry>,
    options: Option<SaveOptions>,
    state: State<'_, SharedState>,
) -> CoreResult<SaveTexturesResult> {
    let options = options.unwrap_or(SaveOptions {
        mode: SaveMode::Overwrite,
        target_path: None,
        namespace: None,
    });

    let (source_path, source_kind, db) = {
        let app = state.read();
        let project = project_for_handle(&app, handle.clone())?;
        (project.source_path.clone(), project.source_kind, app.db.clone())
    };

    let prepared = prepare_textures(textures, &options)?;
    let (original_paths, saved_paths, backup_path) = save_prepared_textures(
        &source_path,
        source_kind,
        prepared,
        &options,
    )?;

    let timestamp = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);

    let (updated_kind, updated_source_path) = {
        let mut app = state.write();
        let project = project_for_handle_mut(&mut app, handle.clone())?;
        project.save_journal.push(SaveJournalEntry {
            timestamp,
            mode: options.mode,
            original_paths: original_paths.clone(),
            saved_paths: saved_paths.clone(),
            backup_path: backup_path.clone(),
        });
        refresh_project_for_paths(&mut app, &db, handle, &saved_paths)?
    };
    invalidate_jar_cache_if_needed(updated_kind, &updated_source_path);

    Ok(SaveTexturesResult {
        saved_count: saved_paths.len() as u64,
        saved_paths,
        original_paths,
        backup_path,
    })
}

/// Batch-save every dirty texture in one call. Each entry carries its own SaveOptions.
/// This lets the UI flush all dirty textures to the same source in a single lock.
#[tauri::command]
#[specta::specta]
pub fn save_batch(
    handle: ProjectHandle,
    textures: Vec<TextureSaveEntry>,
    options: Option<SaveOptions>,
    state: State<'_, SharedState>,
) -> CoreResult<SaveTexturesResult> {
    // Reuse save_textures logic — batch IS save_textures with multiple entries.
    save_textures(handle, textures, options, state)
}

#[tauri::command]
#[specta::specta]
pub fn get_save_journal(
    handle: ProjectHandle,
    state: State<'_, SharedState>,
) -> CoreResult<Vec<SaveJournalEntry>> {
    let app = state.read();
    let project = app
        .projects
        .get(&handle.id)
        .ok_or(CoreError::ProjectNotFound)?;
    Ok(project.save_journal.clone())
}

#[tauri::command]
#[specta::specta]
pub fn rollback_last_save(handle: ProjectHandle, state: State<'_, SharedState>) -> CoreResult<()> {
    let (entry, source_path, source_kind, db) = {
        let mut app = state.write();
        let db = app.db.clone();
        let project = app.projects.get_mut(&handle.id).ok_or(CoreError::ProjectNotFound)?;
        let entry = project
            .save_journal
            .pop()
            .ok_or_else(|| CoreError::Internal("no save to roll back".to_string()))?;
        (entry, project.source_path.clone(), project.source_kind, db)
    };

    let backup = entry
        .backup_path
        .as_deref()
        .ok_or_else(|| CoreError::Internal("save journal entry has no backup".to_string()))?;

    restore_backup_from_known_path(&source_path, source_kind, backup)?;

    let (updated_kind, updated_source_path) = {
        let mut app = state.write();
        refresh_project_for_paths(&mut app, &db, handle, &entry.saved_paths)?
    };
    invalidate_jar_cache_if_needed(updated_kind, &updated_source_path);

    Ok(())
}

#[tauri::command]
#[specta::specta]
pub fn list_project_backups(
    handle: ProjectHandle,
    state: State<'_, SharedState>,
) -> CoreResult<Vec<BackupInfo>> {
    let app = state.read();
    let project = app
        .projects
        .get(&handle.id)
        .ok_or(CoreError::ProjectNotFound)?;

    list_backups(&project.source_path, project.source_kind)
}

#[tauri::command]
#[specta::specta]
pub fn restore_project_backup(
    handle: ProjectHandle,
    backup_path: String,
    state: State<'_, SharedState>,
) -> CoreResult<()> {
    let (source_path, source_kind, db) = {
        let app = state.read();
        let project = app
            .projects
            .get(&handle.id)
            .ok_or(CoreError::ProjectNotFound)?;
        (project.source_path.clone(), project.source_kind, app.db.clone())
    };

    restore_backup_from_known_path(&source_path, source_kind, &backup_path)?;
    let source = load_source(&source_path)?;
    let changed_paths = source.list_entries()?;
    let (updated_kind, updated_source_path) = {
        let mut app = state.write();
        refresh_project_for_paths(&mut app, &db, handle, &changed_paths)?
    };
    invalidate_jar_cache_if_needed(updated_kind, &updated_source_path);
    Ok(())
}

#[tauri::command]
#[specta::specta]
pub fn create_project_backup(
    handle: ProjectHandle,
    state: State<'_, SharedState>,
) -> CoreResult<crate::dto::BackupInfo> {
    let app = state.read();
    let project = app
        .projects
        .get(&handle.id)
        .ok_or(CoreError::ProjectNotFound)?;

    create_backup(&project.source_path, project.source_kind)
}

#[tauri::command]
#[specta::specta]
pub fn restore_project_backup_by_id(
    handle: ProjectHandle,
    backup_id: String,
    state: State<'_, SharedState>,
) -> CoreResult<()> {
    let (source_path, source_kind, db) = {
        let app = state.read();
        let project = app
            .projects
            .get(&handle.id)
            .ok_or(CoreError::ProjectNotFound)?;
        (project.source_path.clone(), project.source_kind, app.db.clone())
    };

    restore_backup_by_id(&source_path, source_kind, &backup_id)?;
    let source = load_source(&source_path)?;
    let changed_paths = source.list_entries()?;
    let (updated_kind, updated_source_path) = {
        let mut app = state.write();
        refresh_project_for_paths(&mut app, &db, handle, &changed_paths)?
    };
    invalidate_jar_cache_if_needed(updated_kind, &updated_source_path);
    Ok(())
}

#[tauri::command]
#[specta::specta]
pub fn list_variants(
    handle: ProjectHandle,
    asset_path: String,
    state: State<'_, SharedState>,
) -> CoreResult<Vec<VariantKey>> {
    let app = state.read();
    let project = app
        .projects
        .get(&handle.id)
        .ok_or(CoreError::ProjectNotFound)?;

    let (namespace, block_name) = blockstate_id_from_asset_path(&asset_path)
        .ok_or_else(|| CoreError::InvalidInput("not a blockstate path".to_string()))?;

    let source = project.source.as_ref();
    let pack = pack_for_project(project);
    let mut cache = project.model_cache.lock().expect("cache poisoned");
    let registry = ModelRegistry::new(source, &mut cache, pack);
    let blockstate = registry.load_blockstate(&namespace, &block_name)?;
    Ok(list_variant_keys(&blockstate))
}

#[tauri::command]
#[specta::specta]
pub fn models_for_texture(
    handle: ProjectHandle,
    asset_path: String,
    state: State<'_, SharedState>,
) -> CoreResult<Vec<ModelRefInfo>> {
    let app = state.read();
    let project = app.projects.get(&handle.id).ok_or(CoreError::ProjectNotFound)?;

    let indexed = texture_index::models_for_texture_path(&project.texture_model_index, &asset_path);
    if !indexed.is_empty() {
        return Ok(indexed);
    }

    let texture_stem = texture_stem_from_entry_path(&asset_path);
    let source = project.source.as_ref();
    let pack = pack_for_project(project);
    let mut cache = project.model_cache.lock().expect("cache poisoned");
    let mut registry = ModelRegistry::new(source, &mut cache, pack);
    find_models_for_texture(&mut registry, &project.entries, &asset_path, &texture_stem)
}

#[tauri::command]
#[specta::specta]
pub fn resolve_renderable(
    handle: ProjectHandle,
    asset_path: String,
    variant_key: Option<String>,
    linked_model_path: Option<String>,
    state: State<'_, SharedState>,
) -> CoreResult<RenderableModel> {
    let app = state.read();
    let project = app.projects.get(&handle.id).ok_or(CoreError::ProjectNotFound)?;

    let resolve_path = linked_model_path.as_deref().unwrap_or(asset_path.as_str());
    let entry = project
        .entries
        .iter()
        .find(|e| e.path == resolve_path)
        .ok_or_else(|| CoreError::AssetNotFound(resolve_path.to_string()))?;

    let source = project.source.as_ref();
    let pack = pack_for_project(project);
    let mut cache = project.model_cache.lock().expect("cache poisoned");
    let mut registry = ModelRegistry::new(source, &mut cache, pack);

    match entry.kind {
        AssetKind::Texture => {
            let mut models =
                texture_index::models_for_texture_path(&project.texture_model_index, &asset_path);
            if models.is_empty() {
                let texture_stem = texture_stem_from_entry_path(&asset_path);
                models = find_models_for_texture(
                    &mut registry,
                    &project.entries,
                    &asset_path,
                    &texture_stem,
                )?;
            }
            if let Some(first) = models.first() {
                let (ns, path) = if let Some((a, b)) = first.model_id.split_once(':') {
                    (a.to_string(), b.to_string())
                } else {
                    (entry.namespace.clone(), first.model_id.clone())
                };
                let resolved = registry.resolve_model(&ns, &path)?;
                compile_renderable(&resolved, &ns, None, &pack, &registry)
            } else {
                compile_texture_preview(&asset_path, &registry)
            }
        }
        AssetKind::BlockModel | AssetKind::ItemModel => {
            let (ns, model_path) = model_id_from_asset_path(&asset_path)
                .ok_or_else(|| CoreError::InvalidInput("invalid model path".to_string()))?;
            let resolved = registry.resolve_model(&ns, &model_path)?;
            compile_renderable(&resolved, &ns, None, &pack, &registry)
        }
        AssetKind::Blockstate => {
            let (ns, block_name) = blockstate_id_from_asset_path(&asset_path)
                .ok_or_else(|| CoreError::InvalidInput("invalid blockstate path".to_string()))?;
            let blockstate = registry.load_blockstate(&ns, &block_name)?;

            if blockstate.multipart.is_some() && blockstate.variants.is_empty() {
                let state = variant_key
                    .as_ref()
                    .map(|key| parse_variant_state(key))
                    .unwrap_or_default();
                let variants = resolve_multipart_models(&blockstate, &state);
                if variants.is_empty() {
                    return Err(CoreError::InvalidInput(
                        "no multipart models matched".to_string(),
                    ));
                }
                return compile_multipart_renderable(&mut registry, &ns, &variants, &pack);
            }

            let variants = collect_variant_models(&blockstate);
            let (variant, _) = variants
                .into_iter()
                .find(|(_, key)| variant_key.as_ref().is_none_or(|vk| vk == key))
                .ok_or_else(|| CoreError::InvalidInput("no variants in blockstate".to_string()))?;
            let (m_ns, m_path) = normalize_model_ref(&variant.model, &ns);
            let resolved = registry.resolve_model(&m_ns, &m_path)?;
            compile_renderable(&resolved, &m_ns, Some(&variant), &pack, &registry)
        }
        _ => Err(CoreError::InvalidInput(
            "asset kind cannot be rendered".to_string(),
        )),
    }
}

#[tauri::command]
#[specta::specta]
pub fn read_recent_logs(max_lines: Option<u32>) -> Result<crate::dto::LogTailResponse, String> {
    let limit = max_lines.unwrap_or(200).clamp(1, 2000) as usize;
    let dir = crate::logging::log_directory()
        .ok_or_else(|| "log directory unavailable".to_string())?;

    let mut entries: Vec<_> = std::fs::read_dir(&dir)
        .map_err(|e| e.to_string())?
        .filter_map(|e| e.ok())
        .filter(|e| {
            e.file_name()
                .to_string_lossy()
                .starts_with("ind3x-art.log")
        })
        .collect();

    entries.sort_by_key(|b| std::cmp::Reverse(b.metadata().and_then(|m| m.modified()).ok()));

    let file_path = entries.first().map(|e| e.path());
    let lines = if let Some(ref path) = file_path {
        read_tail_lines(path, limit).unwrap_or_default()
    } else {
        vec![]
    };

    Ok(crate::dto::LogTailResponse {
        log_dir: Some(dir.to_string_lossy().into_owned()),
        file: file_path.map(|p| p.to_string_lossy().into_owned()),
        lines,
    })
}

fn read_tail_lines(path: &std::path::Path, limit: usize) -> std::io::Result<Vec<String>> {
    use std::fs::File;
    use std::io::{Read, Seek, SeekFrom};

    let mut file = File::open(path)?;
    let file_len = file.metadata()?.len();
    if file_len == 0 {
        return Ok(vec![]);
    }

    const CHUNK: u64 = 16 * 1024;
    let mut pos = file_len;
    let mut buf = Vec::new();

    while pos > 0 {
        let read_size = CHUNK.min(pos);
        pos -= read_size;
        file.seek(SeekFrom::Start(pos))?;
        let mut chunk = vec![0u8; read_size as usize];
        file.read_exact(&mut chunk)?;

        if pos > 0 {
            if let Some(idx) = chunk.iter().position(|&b| b == b'\n') {
                chunk = chunk[idx + 1..].to_vec();
            } else {
                chunk.clear();
            }
        }

        buf.splice(0..0, chunk);

        let complete_lines = buf.iter().filter(|&&b| b == b'\n').count();
        let partial = usize::from(!buf.is_empty() && !buf.ends_with(&[b'\n']));
        if complete_lines + partial >= limit || pos == 0 {
            break;
        }
    }

    let text = String::from_utf8_lossy(&buf);
    let mut lines: Vec<String> = text.lines().map(str::to_string).collect();
    if lines.len() > limit {
        lines = lines.split_off(lines.len() - limit);
    }
    Ok(lines)
}

#[cfg(test)]
mod log_tail_tests {
    use super::read_tail_lines;
    use std::io::Write;

    #[test]
    fn read_tail_lines_returns_last_lines_without_loading_entire_file() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("ind3x-art.log");
        let mut file = std::fs::File::create(&path).expect("create");
        for i in 0..500 {
            writeln!(file, "line-{i}").expect("write");
        }
        drop(file);

        let lines = read_tail_lines(&path, 3).expect("tail");
        assert_eq!(lines, vec!["line-497", "line-498", "line-499"]);
    }
}

#[tauri::command]
#[specta::specta]
pub fn reveal_log_dir(app: tauri::AppHandle) -> CoreResult<()> {
    let dir = crate::logging::log_directory()
        .or_else(|| app.path().app_log_dir().ok())
        .ok_or_else(|| CoreError::Unavailable("log directory unavailable".to_string()))?;

    std::fs::create_dir_all(&dir)?;

    app.opener()
        .open_path(dir.to_string_lossy().to_string(), None::<&str>)
        .map_err(|e| CoreError::Internal(e.to_string()))?;

    Ok(())
}
