mod assets;
mod catalog;
mod helpers;
mod logging;
mod project;
mod save;

#[cfg(test)]
#[path = "tests/integration.rs"]
mod integration_tests;

pub use assets::*;
pub use catalog::*;
pub use logging::*;
pub use project::*;
pub use save::*;

use specta_typescript::Typescript;
use tauri_specta::{collect_commands, Builder};

/// Shared tauri-specta builder — single source for invoke handler + TS export.
pub fn builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(collect_commands![
        get_app_info,
        ping,
        get_sample_pack_path,
        open_source,
        reindex_project,
        invalidate_project_index,
        close_source,
        cancel_index,
        query_assets,
        get_asset_facets,
        query_catalog,
        get_catalog_entry,
        get_catalog_facets,
        resolve_catalog_entry,
        rebuild_project_catalog,
        get_catalog_icon_cache,
        set_catalog_icon_cache,
        invalidate_catalog_icons_for_textures,
        get_project_fingerprint,
        get_asset_entry,
        get_asset_details,
        get_texture_previews_batch,
        reveal_asset_in_folder,
        get_texture_preview,
        get_texture,
        get_texture_binary,
        save_texture_mcmeta,
        save_textures,
        save_batch,
        get_save_journal,
        rollback_last_save,
        list_project_backups,
        restore_project_backup,
        create_project_backup,
        restore_project_backup_by_id,
        list_variants,
        models_for_texture,
        resolve_renderable,
        read_recent_logs,
        reveal_log_dir,
    ])
}

pub fn export_typescript(path: &str) {
    builder()
        .export(
            Typescript::default().header(
                "// AUTO-GENERATED by export_bindings — do not edit manually.\n\
                 // Run: npm run gen:types",
            ),
            path,
        )
        .expect("failed to export tauri-specta bindings");
}
